[ 2023-04-14 08:43:06,457 ] 224 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3000
 * Running on http://192.168.211.237:3000
[ 2023-04-14 08:43:06,457 ] 224 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2023-04-14 08:43:53,769 ] 224 werkzeug - INFO - 127.0.0.1 - - [14/Apr/2023 08:43:53] "GET / HTTP/1.1" 200 -
[ 2023-04-14 08:43:54,005 ] 224 werkzeug - INFO - 127.0.0.1 - - [14/Apr/2023 08:43:54] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2023-04-14 08:44:00,191 ] 224 werkzeug - INFO - 127.0.0.1 - - [14/Apr/2023 08:44:00] "GET /predictdata HTTP/1.1" 200 -
[ 2023-04-14 08:44:10,767 ] 1744 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\AWS_CI-CD\src\pipeline\predict_pipeline.py", line 18, in predict
    data_scaled=preprocessor.transform(features)
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\sklearn\utils\_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\sklearn\compose\_column_transformer.py", line 800, in transform
    Xs = self._fit_transform(
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\sklearn\compose\_column_transformer.py", line 658, in _fit_transform
    return Parallel(n_jobs=self.n_jobs)(
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\sklearn\utils\parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\joblib\parallel.py", line 1088, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\joblib\parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\joblib\parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\joblib\_parallel_backends.py", line 597, in __init__
    self.results = batch()
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\sklearn\utils\parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\sklearn\pipeline.py", line 876, in _transform_one
    res = transformer.transform(X)
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\sklearn\pipeline.py", line 658, in transform
    Xt = transform.transform(Xt)
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\sklearn\utils\_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\sklearn\preprocessing\_encoders.py", line 927, in transform
    if self._drop_idx_after_grouping is not None:
AttributeError: 'OneHotEncoder' object has no attribute '_drop_idx_after_grouping'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Dell\Desktop\AWS_CI-CD\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Dell\Desktop\AWS_CI-CD\app.py", line 37, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
  File "C:\Users\Dell\Desktop\AWS_CI-CD\src\pipeline\predict_pipeline.py", line 23, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [C:\Users\Dell\Desktop\AWS_CI-CD\src\pipeline\predict_pipeline.py] line number [18] error message['OneHotEncoder' object has no attribute '_drop_idx_after_grouping']
[ 2023-04-14 08:44:11,239 ] 224 werkzeug - INFO - 127.0.0.1 - - [14/Apr/2023 08:44:11] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
